# Generated by Django 5.2.7 on 2025-11-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customernumbering',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
